spring.application.name=newstification
spring.security.user.name=elek
spring.security.user.password=kecske

app.user.email=elek@teszt.com
app.user.slack-url=https://hooks.slack.com/services/YOUR/TEST/WEBHOOK

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=elek@teszt.com
spring.mail.password=kecske
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.enable=true
